from math import *
import random


def textrealiser():
    abc = input("Type any text in.\n")

    abc = str(abc)  # converting the input to a string in case of text and digits being used.

    if abc.islower() is True:
        print("the text is lowercase!")

    if abc.isupper() is True:
        print("the text is Uppercase!")

    if abc.isupper() is False and abc.islower() is False and abc.isnumeric() is False and abc.isdigit() is False:
        print("The text is mixed!!!")  # so many "and" uses to make sure that one output is chosen.

    if abc.isnumeric() is True:
        print("these are numbers!")


def numbercompare():
    a = input("put the first number in.\n")
    b = input("put the second number in.\n")
    c = input("put the third number in.\n")

    choice = input("do you want the biggest or the smallest number? [big/small/both]\n")

    str(choice)
    str(a)
    str(b)
    str(c)

    if choice == "big":
        print("this is the biggest number: " + max(a, b, c))

    if choice == "small":
        print("this is the smallest number: " + min(a, b, c))

    if choice == "both":
        print("this is the biggest number: " + max(a, b, c))
        print("this is the smallest number: " + min(a, b, c))


def firstsimplecalculator():

    number1 = input("input the first number: \n")
    number2 = input("input the second number: \n")
    choice = input("what do you want to do with them? [add/subtract/multiply/divide/squareroot/exponentiate]\n")

    if number1.isnumeric() is False and number2.isnumeric() is False:
        print("both inputs are not numbers or contain a space.")
        exit()

    if number1.isnumeric() is False:
        print("the first input is not a number or contains a space.")  # The 3 if statements check if
        exit()  # the inputs are numeric to not cause errors

    if number2.isnumeric() is False:
        print("the second input is not a number or contains a space.")
        exit()

    number1 = int(number1)
    number2 = int(number2)  # Changing the variables from strings into integers to make the math functions possible.

    added = number1 + number2
    subtracted = number1 - number2
    multiplied = number1 * number2
    divided = number1 / number2  # These are just variables that i want to use
    sqrooteda = sqrt(number1)  # in later code not to make mess.
    sqrootedb = sqrt(number2)
    exponentiated = pow(number1, number2)

    if choice == "add":
        print(str(number1) + " + " + str(number2) + " = " + str(added))

    if choice == "subtract":
        print(str(number1) + " - " + str(number2) + " = " + str(subtracted))

    if choice == "multiply":
        print(str(number1) + " * " + str(number2) + " = " + str(multiplied))

    if choice == "divide":
        print(str(number1) + " / " + str(number2) + " = " + str(divided))

    if choice == "squareroot":
        print(str(number1) + " square rooted is " + str(sqrooteda))
        print(str(number2) + " square rooted is " + str(sqrootedb))

    if choice == "exponantiate":
        print(str(number1) + " ^ " + str(number2) + " = " + str(exponentiated))


def dice_sim():
    choice = input("Do you want to roll the dice? yes/no\n")

    while choice == "yes":
        print(random.randint(1, 6))
        choice = input("wanna roll the dice again?\n")

    else:
        print("see you next time!")


def guessthenumber():

    x = random.randint(0, 100)
    y = 101
    print("Try to guess the number randomly generated by the computer!\n")
    while y != x:
        y = input("Type in your guess.\n       ")

        y = int(y)

        if x == y:
            print("You win!")

        if y < x:
            print("Your number is too low.")

        if y > x:
            print("Your number is too high.")


programs = ["Text Realiser", "Compare Numbers", "Calculator", "Dice Simulator", "GTN Game"]

endprogram = "abc"

while endprogram != "":
    print(" ")
    print(programs)
    answer = input("\nWhat program do you want to run? (choose from the list above ;p)[Exit = Press enter]\n")

    if answer == "Text Realiser":
        textrealiser()
        endprogram = input("If you want to end the program press enter, if you want to keep going type any text in.\n")

    if answer == "Compare Numbers":
        numbercompare()
        endprogram = input("If you want to end the program press enter, if you want to keep going type any text in.\n")

    if answer == "Calculator":
        firstsimplecalculator()
        endprogram = input("If you want to end the program press enter, if you want to keep going type any text in.\n")

    if answer == "Dice Simulator":
        dice_sim()
        endprogram = input("If you want to end the program press enter, if you want to keep going type any text in.\n")

    if answer == "GTN Game":
        guessthenumber()
        endprogram = input("If you want to end the program press enter, if you want to keep going type any text in.\n")

    if answer == "":
        exit()
