import random

x = random.randint(0, 100)
y = 101
print("Try to guess the number randomly generated by the computer!\n")
while y != x:
    y = input("Type in your guess.\n       ")

    y = int(y)

    if x == y:
        print("You win!")
        exit()

    if y < x:
        print("Your number is too low.")

    if y > x:
        print("Your number is too high.")
